name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.11", "3.10"]

    steps:
    - uses: actions/checkout@v4

    - name: Check initial OpenSSL version
      run: |
        openssl version
        openssl version -a

    - name: Install OpenSSL dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev openssl

    - name: Check installed OpenSSL version
      run: |
        openssl version
        openssl version -a

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Run tests
      run: uv run pytest
