name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13","3.12", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Print versions
      run: |
        openssl version
        openssl version -a

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Run tests
      run: uv run --python ${{ matrix.python-version }} --frozen pytest
